# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/GUI_TEST/my_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPalette, QBrush

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(900, 600)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1500, 1000))

#newly added
        oImage = QImage("medical-healthcare-background.jpg")
        sImage = oImage.scaled(QtCore.QSize(900,600))                   # resize Image to widgets size
        palette = QPalette()
        palette.setBrush(10, QBrush(sImage))                     # 10 = Windowrole
        self.setPalette(palette)
#

        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo_only.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.central = QtWidgets.QWidget(MainWindow)
        self.central.setObjectName("central")
        self.clearFace = QtWidgets.QPushButton(self.central)
        self.clearFace.setGeometry(QtCore.QRect(350, 403, 60, 31))
        self.clearFace.setObjectName("clearFace")
        self.faceImage = QtWidgets.QLabel(self.central)
        self.faceImage.setGeometry(QtCore.QRect(90, 158, 320, 240))
        self.faceImage.setMinimumSize(QtCore.QSize(320, 240))
        self.faceImage.setStyleSheet("background-color: rgb(220, 240, 240);")
        self.faceImage.setAlignment(QtCore.Qt.AlignCenter)
        self.faceImage.setObjectName("faceImage")
        self.label_title = QtWidgets.QLabel(self.central)
        self.label_title.setGeometry(QtCore.QRect(130, 80, 661, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_title.setAutoFillBackground(False)
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.selectFace = QtWidgets.QPushButton(self.central)
        self.selectFace.setGeometry(QtCore.QRect(90, 403, 141, 31))
        self.selectFace.setObjectName("selectFace")
        self.label_2 = QtWidgets.QLabel(self.central)
        self.label_2.setGeometry(QtCore.QRect(110, 120, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tongueImage = QtWidgets.QLabel(self.central)
        self.tongueImage.setGeometry(QtCore.QRect(490, 158, 320, 240))
        self.tongueImage.setMinimumSize(QtCore.QSize(320, 240))
        self.tongueImage.setStyleSheet("background-color: rgb(220, 240, 240);")
        self.tongueImage.setAlignment(QtCore.Qt.AlignCenter)
        self.tongueImage.setObjectName("tongueImage")
        self.label_3 = QtWidgets.QLabel(self.central)
        self.label_3.setGeometry(QtCore.QRect(500, 120, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.clearTongue = QtWidgets.QPushButton(self.central)
        self.clearTongue.setGeometry(QtCore.QRect(750, 403, 60, 31))
        self.clearTongue.setObjectName("clearTongue")
        self.file_path_tongue = QtWidgets.QLabel(self.central)
        self.file_path_tongue.setGeometry(QtCore.QRect(490, 440, 320, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.file_path_tongue.setFont(font)
        self.file_path_tongue.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.file_path_tongue.setObjectName("file_path_tongue")
        self.selectTongue = QtWidgets.QPushButton(self.central)
        self.selectTongue.setGeometry(QtCore.QRect(490, 403, 151, 31))
        self.selectTongue.setObjectName("selectTongue")
        self.label_5 = QtWidgets.QLabel(self.central)
        self.label_5.setGeometry(QtCore.QRect(420, 490, 90, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.checkHealthStatus = QtWidgets.QPushButton(self.central)
        self.checkHealthStatus.setGeometry(QtCore.QRect(350, 520, 191, 51))
        self.checkHealthStatus.setObjectName("checkHealthStatus")
        self.file_path_face = QtWidgets.QLabel(self.central)
        self.file_path_face.setGeometry(QtCore.QRect(90, 440, 320, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.file_path_face.setFont(font)
        self.file_path_face.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.file_path_face.setObjectName("file_path_face")
        self.label = QtWidgets.QLabel(self.central)
        self.label.setGeometry(QtCore.QRect(320, 10, 240, 70))
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.central)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "iDD - Intelligent Disease Detection"))
        self.clearFace.setText(_translate("MainWindow", "Clear"))
        self.faceImage.setText(_translate("MainWindow", "Face Image"))
        self.label_title.setText(_translate("MainWindow", "Check your Health Status in 3 Steps!"))
        self.selectFace.setText(_translate("MainWindow", "Select Image"))
        self.label_2.setText(_translate("MainWindow", "STEP 1. Select the Face"))
        self.tongueImage.setText(_translate("MainWindow", "Tongue Image"))
        self.label_3.setText(_translate("MainWindow", "STEP 2. Select the Tongue"))
        self.clearTongue.setText(_translate("MainWindow", "Clear"))
        self.file_path_tongue.setText(_translate("MainWindow", "Tongue Image Path"))
        self.selectTongue.setText(_translate("MainWindow", "Select Image"))
        self.label_5.setText(_translate("MainWindow", "STEP 3"))
        self.checkHealthStatus.setText(_translate("MainWindow", "Check Health Status!"))
        self.file_path_face.setText(_translate("MainWindow", "Face Image Path"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
